### ISSUE TITLE
Support for vertical sync / FPS limitations

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#1648]
As the title says, the current Neos tries to record the highest frame rate possible, especially when used on a desktop.
So if you can put a vertical sync, or if you are strict, a frame rate limit on it, you can give the CPU/GPU a break for that.

タイトルの通りですが、特にデスクトップで使用する場合、現在のNeosでは可能な限り高いフレームレートを記録しようとします。
そのため、垂直同期、もし厳しければフレームレートの制限を掛けることができるのであればその分CPU/GPUを休ませることができます。
## Is your feature request related to a problem? Please describe.
I don't think that's particularly relevant.

## Describe the solution you'd like
It might be a good idea to add a (Desktop Integration) item in the settings section, from which the value and VSYNC enablement can be controlled by a checkbox or value input.
Alternatively, if it needs to be fixed at startup (difficult to set dynamically), it may be possible to set it only by changing it from command-line-arguments or NeosLauncher.
設定の項目の中に(Desktop Integration)の項目を追加して、そこから値やVSYNCの有効化をチェックボックスや値の入力によってコントロールできるようにすると良いのかもしれません。
もしくは、起動時に固定化する必要がある（動的に設定することが困難）のであれば、command-line-argumentsやNeosLauncherから変更することでのみ設定することでもよいかもしれません。

## Describe alternatives you've considered
I checked to see if there is a setting to limit FPS in the startup options that can be set from the Unity side. There was not.

**Comment by shadowpanther** [comment]
Might be related: in VR, when I remove my HMD, the screen goes black (the rendering mostly stops), but FPS skyrockets  until it maxes out the CPU. Right now, I can register 180-200 FPS, 100% CPU usage, 9% GPU usage. My display's framerate is 60Hz, HMD is 80Hz. Limiting the framerate to the main output device would free up the CPU.

**Comment by shiftyscales** [comment]
From what I've learned from talking with @shadowpanther , it appears that this issue is specific to the Oculus runtime, and Unity renderer. From what shadow also noted about other Unity VR applications, the rendering is disabled/shut off out right while the headset is idle/there is no user present. (It rapidly flickers the last frames rendered to the framebuffer in Unity-based applications.)

On my Quest, it continues to render but at a heavily throttled framerate around 10-15. So this might also specifically be an issue related to the Oculus Rift S. Which headset are you using @kazu0617 ? 

Would it be possible to throttle the FrooxEngine while the user is not present and/or in the absence of an active rendering thread @Frooxius ?

**Comment by kazu0617** [comment]
> From what I've learned from talking with @shadowpanther , it appears that this issue is specific to the Oculus runtime, and Unity renderer. From what shadow also noted about other Unity VR applications, the rendering is disabled/shut off out right while the headset is idle/there is no user present. (It rapidly flickers the last frames rendered to the framebuffer in Unity-based applications.)
> 
> On my Quest, it continues to render but at a heavily throttled framerate around 10-15. So this might also specifically be an issue related to the Oculus Rift S. Which headset are you using @kazu0617 ?
> 
> Would it be possible to throttle the FrooxEngine while the user is not present and/or in the absence of an active rendering thread @Frooxius ?

I'm using Index and Quest1/2, and mainly use Index.
But in Index doesn't thottled framelate I think(sometime occur but just with heavily Logix/Component.

**Comment by Frooxius** [comment]
The new desktop mode in 2021.3.28.524 now activates V-Sync, which should solve this problem! Thank you for logging this issue!

**Comment by shadowpanther** [comment]
The part reported by myself is not fixed - when in VR mode and out of the headset (the screen is blacked out) the FPS aren't limited and the CPU is at 100%.
Oculus Rift S, Oculus runtime.
<img width="1920" alt="Screenshot 2021-03-28 21 51 55" src="https://user-images.githubusercontent.com/675104/112764210-2b951880-9010-11eb-8daf-b4b2246a2adf.png">
<img width="1920" alt="Screenshot 2021-03-28 21 52 18" src="https://user-images.githubusercontent.com/675104/112764216-32bc2680-9010-11eb-934a-abb787ed101a.png">

(Notice the FPS counter added by Steam in the top-left corner of Neos window)
