### ISSUE TITLE
Reflection probes brightly emissive under Linux

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#1697]
## Describe the bug
While reflection probes are in use under Linux, they appear fully emissive, and will overtake/render on top of everything else in the area they cover.

## To Reproduce
- Under Linux go to a world with reflection probes or create one
- Toggling the refelction probe off will prevent the rendering issue

## Expected behavior
- Reflection probes render as expected

## Screenshots / Video
https://cdn.discordapp.com/attachments/439421735474036738/800296427615158282/Neos_material_test_2.webm

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.1.17.1026
 - Neos Platform: Linux
 - Regression: Not known- it sounds like this might have always been an issue under Linux since reflection probes were added

## Additional context
In both reported cases, the users have been in screen mode under Linux.

## Reporters:
happysmash27# 7060 
Polychrome# 3900

**Comment by Silvea12** [comment]
For a summary of info so far on my testing: RX Vega M GH (custom chip for nucs, based off of the RX Vega M) is having the same blowout issues with reflection probes.

Driver being used is AMDGPU, running through MESA, with the Valve ACO shader compiler, running Manjaro Linux (a variant on Arch Linux, and for all intents and purposes can be treated as the same system if up to date)

Trying through WINE (for the hell of it, via Proton 5.13-6) crashes on load while trying to initialize NetworkManager. Could likely be fixed with ProtonTricks to install missing windows components, however I don't know if this is worth pursuing.

The Steam Linux Runtime (a sandbox to run games in with a standardized set of system libraries, to try and alleviate compatibility issues) still displays the same blowout issues.

Additionally, in another message from Polychrome elsewhere it was mentioned that this also fails with the AMD Radeon RX5800 XT on Ubuntu 20.10, but works flawlessly with the NVidia GeForce GTX1070 on Ubuntu 18.04.5. So chances are it's an AMD-specific issue.

I can test further with other drivers, platforms, further try with WINE etc if required, and can run traces/renderdoc/etc as required (just let me know exactly what you want pulled out)

**Comment by Enverex** [comment]
Here's an example of what the tutorial looks like after the world has finished loading.

![image](https://user-images.githubusercontent.com/958670/108234740-01ad2400-713d-11eb-8da4-df38965349fc.png)

Radeon RX Vega 64 (Mesa 20.3.3, DRM 3.40.0, 5.10.9-arch1-1, LLVM 11.0.1).

**Comment by Develon5543** [comment]
Sorry to bother you, but any updates on this? I haven't been able to use Neos VR at all since I've gotten my headset. Since the tutorial won't load at all, it's not very easy to get started. I'm just sort of venting my frustrations because I really want to enjoy this software.

**Comment by Frooxius** [comment]
Don't have a solution for this yet, sorry, but we'll probably disable reflection probes on Linux for the time being before this gets prioritized.

**Comment by Frooxius** [comment]
Ended up finding a fix while I was poking around to disable it, it was just a typo setting wrong flags for the OpenGL HDR textures. Fixed in 2021.3.25.399!

**Comment by Silvea12** [comment]
Still an issue, see the attached image. On windows on the same hardware, there are no issues. Hardware unchanged from my previous comment.

![image](https://user-images.githubusercontent.com/3120639/121955926-dc0af100-cda3-11eb-934e-6cec5bc5e850.png)

**Comment by Frooxius** [comment]
Can you check what's the texture format of those reflection probe textures?

**Comment by Silvea12** [comment]
> Can you check what's the texture format of those reflection probe textures?

How would I go about doing that? I'm available in the Neos Discord.

**Comment by Frooxius** [comment]
On the ReflectionProbe go to the "BakedCubemap" field and click the upwards arrow to open the inspector for the cubemap. The format will be listed there.

**Comment by H3BO3** [comment]
There's actually no reflection probe. We determined it was an issue with a mirror material under the floor to provide realtime reflections, and I know mirrors are buggy on Linux. Closing this issue.
