### ISSUE TITLE
Channel Packing Detailed info request

### ISSUE THREAD

**Issue by eduprimowl** [Neos-Metaverse/NeosPublic#1776]
## Where have you searched for this information before making this issue?
Google, Duckduckgo, Tut vids, Discord folks

## Which part of the system do you need information on?
Texture Channel Packing and Materials

## What information do you need to know?
I am looking to get detailed information on not just the Metallic Smoothness but also if any other Material Texture inputs also utilize Channel Packing.

From the info that has been passed on metal utilizes RGB and the Smoothness on the Alpha.
But is the RGB Metallic using all of the RGB channels and providing Metallic Tint or just a single RGB channel?

Does Neos VR currently utilize RMA or another RGBA channel combo setup Channel Packing for any of it's Materials for texture inputs on Ambient Occlusion or Emissive.?

## Do you plan to format and contribute the provided information to Wiki?
I will attempt to do so.

**Comment by eduprimowl** [comment]
![2021-02-25 14 26 14](https://user-images.githubusercontent.com/9915939/109227210-92ab7d00-7785-11eb-9914-3afbd866309e.jpg)
![2021-02-25 14 27 03](https://user-images.githubusercontent.com/9915939/109227218-94754080-7785-11eb-811e-e4e75216fff5.jpg)
![2021-02-25 14 56 53](https://user-images.githubusercontent.com/9915939/109227228-9808c780-7785-11eb-9dcc-ddb860172a57.jpg)
![2021-02-25 15 15 22](https://user-images.githubusercontent.com/9915939/109227232-9a6b2180-7785-11eb-9544-2bacd1f14882.jpg)

**Comment by Geenz** [comment]
Hey there!

Thanks for the report, by and large for the standard PBS shaders we follow the Unity model almost verbatim.

However, I definitely agree that we need to add this to the wiki, along with documenting various other shaders available in Neos today.  I'll be kicking off this documentation effort soon - however input is appreciated to help accelerate the process.

Thank you very much for your notes thus far on this!

**Comment by eduprimowl** [comment]
Ahh I see as per this
https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@7.1/manual/lit-shader.html
I see PBS Metallic therefore is
R: Metalness
G: Occlusion/Height
A: Smoothness

Odd though that on the doublesided metallic occlusion aims for the Red

**Comment by TehTurk** [comment]
I'm going to close this issue since it looks like it was resolved :)

**Comment by ProbablePrime** [comment]
@TehTurk was the information posted on the wiki/documentation?

That's what Geenz was talking about. Therefore I don't think it was resolved as Geenz hasn't done the documentation yet. Is it resolved?

**Comment by TehTurk** [comment]
Oop misread, I'm going through a bunch of the issues and doing some cleanup apologies. Let me at least link for the PBR Shaders on the wiki.

**Comment by ProbablePrime** [comment]
I appreciate the cleanup effort. thank you!

**Comment by TehTurk** [comment]
Closed at request of @eduprimowl
