### ISSUE TITLE
Fullbody trackers still affect IK even when in F8 desktop mode

### ISSUE THREAD

**Issue by ohzee00** [Neos-Metaverse/NeosPublic#1889]
## Describe the bug
When switching from VR to the new desktop mode, trackers will continue to act on the IK, making your character warped between your desktop head position and your tracked hips/feet.

## Relevant issues
None found.

## To Reproduce
1. Go into Neos with fullbody
2. Switch over to F8 desktop mode
3. Observe that your body hates being associated with your head

## Expected behavior
Fullbody trackers should be disabled when going to F8 desktop mode to avoid issues.

## Screenshots / Video
Sadly none that I have on me.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.25.446 (Haven't had a opportunity to test with the newest version but should still be happening)
 - Neos Platform: Windows
 - Link to reproduction World/Item: None
 - Regression: Unsure, my guess is no due to desktop mode being new

## Additional context
Funny enough, lasers and hand posing still worked and I was able to still interact with menus/with my lasers despite this. So while it isn't exactly game breaking, it does look really odd.

## Reporters:
AshtonSparx#5050

**Comment by Frooxius** [comment]
Fixed in 2021.3.30.508, thanks for reporting!

**Comment by Hayden-da-Serg** [comment]
I'm still experiencing this issue, the only things I can think of that are different is that I'm using Vive 3.0 trackers and that I have my tracker roles set in SteamVR.

**Comment by shiftyscales** [comment]
You also presumably have your pose mode Logix on your avatar, @Hayden-da-Serg - have you tested with regular avatars like the Neos bot to see if it occurs on them too?

**Comment by Hayden-da-Serg** [comment]
I actually don't have that on the avatars I've been using, as I transferred it over to my modules system a long while ago, so none of the values on my VRIK are being driven while the module is not present. I will try this the next time I get the chance though.
So far I have experienced this since I've gotten trackers for full body.

**Comment by Hayden-da-Serg** [comment]
@shiftyscales so I haven't gotten to test this with the Neos bot, however I'm currently using a completely default avatar that has no Logix on it whatsoever, and it still is in full body while switching to screen mode, I have to turn off my trackers while standing if I want to not have them effect my avatar while in screen mode.

**Comment by Readun** [comment]
Same Problem for me aswell (Vive tracker 2.0) (Never actually looked into github for this issue yet....)
It appears to be randomly working sometimes, sometimes not. Sometimes it helps to reload the avatar aswell.

**Comment by ModernBalloonie** [comment]
I'm still experiencing this as of now, and I use a Kinect 2.0 emulating Vive trackers.

**Comment by shiftyscales** [comment]
I've think isolated what this issue seems to be caused by, @Frooxius.

It appears that the AlwaysUseTrackersWhenHorizontal property on VRIKAvatar will remain in effect even if the trackers are turned off/the trackers are marked as active even if turned off.

I had this occur by the following steps:
- While seated, and in full-body I:
-- Took off my headset
-- Walked across the room
-- Turned off the hip tracker
-- Turned off the feet trackers
-- Returned to my desk and entered desktop mode

Notes:
- Despite being powered off, the `IsActive` propery on the TrackedDevicePositioner for the Hips, Left Foot, and Right Foot are still checked/active.
- When I unchecked AlwaysUseTrackersWhenHorizontal my avatar was returned to its proper position in desktop mode, but re-enabling the setting caused the avatar to be moved right back.
- There are valid use-cases for wanting the tracked positions to remain in effect while the physical trackers are off, e.g. if they run out of power while you are seated/lying down
-- The main issue seems like it might stem from the trackers being turned off while out of headset/a significant distance away
