### ISSUE TITLE
Message not being delivered to contacts

### ISSUE THREAD

**Issue by Electronus** [Neos-Metaverse/NeosPublic#1922]
## Describe the bug
users will sometimes not receive messages.(Text voice and invites), until next restart. last time i saw it, they were unable to recive messages from four different people. 
## Relevant issues
#1916 may be relevant not sure. 

## To Reproduce
1. Send someone a message of anytype
2. Ask if they have received it outside of neos. 
3. restarting seems to fix it.

## Expected behavior
they receive the message near instantly. (depending on the message type this may take longer)

## Bug information (please complete the following information):
 - How often does it happen: Sometimes
 - Does the bug persist after restarting Neos? No, I think. 
 - Neos Version: 2021.3.30.508 (last time i was on and sent a message)
 - Neos Platform: Windows
 - Regression: Yes, not sure what build there has been many and this is a rareish bug.

## Reporters:
Electronus, KierDran

**Comment by shiftyscales** [comment]
Hmm- not sure that this is related to #1916. I've experienced #1916 once and that issue appears to persist through restarts, but also, notifications still come in from the user, it's just that the message history is stuck 'loading'. #1916 also persists across restarts.

Do you know of any specific conditions when this issue occurs, or do you have logs from sessions in which it has occurred, @Electronus?

**Comment by Electronus** [comment]
I don't unfortunately i simply have launched the game to many times to tell. Atremis or Gmodude may have easier to get logs. 

I dont know of any specific conditions either. Ill see if i can track down one of my logs where i couldn't see messages.

**Comment by Frooxius** [comment]
It might be related to those yeah. Can you get me any logs from the people who have failed to receive the messages?

Is there any odd behavior on your end when this happens? E.g. the message taking a while to send?

**Comment by Electronus** [comment]
Unfortunately I dont have those logs. I will try to get them no promises. 

No nothing odd on my end, it looks completely normal, even voice message sync.

**Comment by Frooxius** [comment]
I've made tweaks to retry logic in 2021.4.2.690 and added more throughput to the cloud infrastructure, seems like the database was getting too throttled in some cases. Reopen if the issues still persist!

**Comment by shiftyscales** [comment]
Reopening this issue, as it appears cases of this are still cropping up.

The logs of myself and the recipient (Cyro) are clean of any indiciation of problem, but I had sent him some messages and a world invite at around 3:05pm PT today, which he was unable to read/see until he had restarted Neos.

On my end the messages appeared yellow as though they had been sent properly.

This also appears to be one of the frustrations that prompted issue #2067 to be opened.

**Comment by FroppyVR** [comment]
Posting to say i've been having this issue lately, every message i've received has failed to come through until i restart neos.

April 30th - a text message from Raith
May 2nd - a voice message from TheCrowDevilsBK and a voice message from ProbablePrime
May 5th - a text message from Maddmaxkz 

Messages from Neos bot work as expected, but all others fail until restart, timestamps appear correct. (time sent, not time received.)  I have four logs for the may 5th(message sent) and four logs for may 6th (message received), but i'm unable to find anything of note as i'm not sure what to be searching for (the logs are fairly large.) Will share if required, but i think attempting to reproduce in a new log may be better.

**Comment by Thewolfmate** [comment]
I am also popping in to say i have been getting this bug recently as well, coming to add a little of my findings on this bug.

So it seems that i am still recieving the messages in neos, because i got a message from user The Honeybee with an invite, but i didnt get sent the invite until after i actually clicked on the message and loaded up the previous messages from that user. Then and only then do the messages just stop being recieved and i have to restart to reload the message window. This has been recreated several times and That seems to be how my experience has been going. Any other info i can provide i will gladly give.

AjaxWolf on Neos

**Comment by Hopolis** [comment]
This problem is killing me. I am unable to receive messages or invites from anyone, echo and other commands return nothing from the neos bot as well. I only see them once I restart neos but after that point if I want to see anymore, I need to restart again. It's been spotty but at some point last night, I just stopped getting anything.

**Comment by Frooxius** [comment]
Can you send me logs as well please from when it occurred? I think I see some things in @Thewolfmate that are potential leads, but having more information helps.

**Comment by Frooxius** [comment]
Thanks for the logs! I'm relatively confident I found the culprits, I've pushed a patch 2021.5.8.440 and one to the cloud which should hopefully fix those issues.

I'm going to close it for now, but please keep an lookout and see if you run into the problem again! I added more diagnostics just in case, so if there are still problems they'll hopefully help diagnosing the causes.

**Comment by Thewolfmate** [comment]
Hello hello, so as it turns out the patch that was pushed out did not seem to fix the issue I was having, and i double checked with Hopolis and it seems both of our issues are still present.

**Comment by shiftyscales** [comment]
Hey @Thewolfmate if you and @Hopolis could please provide logs from sessions this has occurred in, that would be appreciated, thanks. As Frooxius noted, he's added additional diagnostics that should help in isolating the issue if you provide those logs.

**Comment by Hopolis** [comment]
This should be it.

[DESKTOP-GL3BCN6 - 2021.5.8.445 - 2021-05-08 15_57_50.log](https://github.com/Neos-Metaverse/NeosPublic/files/6446669/DESKTOP-GL3BCN6.-.2021.5.8.445.-.2021-05-08.15_57_50.log)

**Comment by Frooxius** [comment]
@Hopolis Thanks! How exactly does this occur? It seems like you're hitting the rate limiting on the cloud due to too many requests to fetch the messages. Does it occur on the first startup? Or do you restart Neos several times within a short period of time?

Do you have anything else running on your computer/network that could be fetching your messages? E.g. headless signed with the same account that you're using?

**Comment by Thewolfmate** [comment]
Some more logs, if they help at all, including the ones from today after the patch
[DESKTOP-T98HJEH - 2021.5.8.445 - 2021-05-08 17_58_16.log](https://github.com/Neos-Metaverse/NeosPublic/files/6446699/DESKTOP-T98HJEH.-.2021.5.8.445.-.2021-05-08.17_58_16.log)
[DESKTOP-T98HJEH - 2021.5.8.445 - 2021-05-08 17_49_49.log](https://github.com/Neos-Metaverse/NeosPublic/files/6446700/DESKTOP-T98HJEH.-.2021.5.8.445.-.2021-05-08.17_49_49.log)
[DESKTOP-T98HJEH - 2021.5.6.453 - 2021-05-07 04_27_07.log](https://github.com/Neos-Metaverse/NeosPublic/files/6446702/DESKTOP-T98HJEH.-.2021.5.6.453.-.2021-05-07.04_27_07.log)
[DESKTOP-T98HJEH - 2021.4.29.1307 - 2021-05-03 21_23_06.log](https://github.com/Neos-Metaverse/NeosPublic/files/6446703/DESKTOP-T98HJEH.-.2021.4.29.1307.-.2021-05-03.21_23_06.log)

Some may be repeats, and if they are thats my mistake, but ill add these to the ones i have provided previously

**Comment by Hopolis** [comment]
@Frooxius I don't restart at all, and my headless isn't local. I just log in and never get anything.

**Comment by Hopolis** [comment]
Getting messages!! :>

**Comment by shiftyscales** [comment]
Wolf, and Hop have confirmed they got their messages. Closing this issue.

**Comment by ThatOneTeshari** [comment]
Heya, been having some message issues for a while now. Going to just slip my log in here and hope a fix for the oddness is found. I'll provide additional information if needed but from looking it over, sounds like the same issue. 

[BANBANS-PC - 2021.5.29.1365 - 2021-06-06 17_16_32.log](https://github.com/Neos-Metaverse/NeosPublic/files/6621278/BANBANS-PC.-.2021.5.29.1365.-.2021-06-06.17_16_32.log)

**Comment by Frooxius** [comment]
Thanks for the report! I'll be prioritizing switch to SignalR for message delivery soon, which should heavily improve the reliability. It looks like the current system is reaching its limits in terms of scalability (at least without us throwing lots of money at it), so it's about the time to switch to a more efficient solution.

It'll likely take a bit, but it should help improve things significantly in the long term.

**Comment by ThatOneTeshari** [comment]
I've started to get messages again which is awesome.

**Comment by Frooxius** [comment]
We've now moved the messaging system to SignalR in 2021.7.6.1154, which should greatly improve the robustness of the system, so hopefully this will help resolve the last of those issues!

I'm closing this for now, but let us know if you still run into some issues!
