### ISSUE TITLE
Logix uneditable when on worn avatar

### ISSUE THREAD

**Issue by dotuser** [Neos-Metaverse/NeosPublic#1982]
## Describe the bug
Prior to the bugfix for accidentally creating loops on interface cards, editing logix which are parented under a self-worn avatar was possible, now nodes do not allow interaction with inputs/outputs.

## Relevant issues
#1955 

## To Reproduce
Wear any avatar with logix under it
Unpack said logix
Attempt to reroute wires/interact with node input/outputs

## Expected behavior
Should be able to route wires.

## Screenshots / Video
N/A

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.6.931
 - Neos Platform: Any
 - Regression: Worked before recent interface card changes

## Additional context
N/A

## Reporters:
Polaris / @dotUser # 0001
Hayden# 3180

**Comment by ukilop** [comment]
This includes simple grabbing, just grabbing a node with offhand prevents you from grabbing a wire with a logix tip.
I have a habit of sometimes grabbing nodes with one hand to grab the wire with my other hand, especially when doing simple logix tests, so this being no-longer doable was a interesting discovery.

**Comment by Frooxius** [comment]
Fixed in 2021.4.9.1114, sorry for the trouble!

**Comment by ukilop** [comment]
can now edit logix when on toolshelf for example, but still not when grabbed

**Comment by TehTurk** [comment]
Huh? Can you clarify a bit more ukilop?

**Comment by ukilop** [comment]
putting logix on toolshelf, u can grab a wire off of it, you cant if the node is just held in hand

**Comment by TehTurk** [comment]
Ah you mean like when your holding an interface card and need to drag a logix connection from it? Or no

**Comment by ukilop** [comment]
yes, but also nodes

**Comment by TehTurk** [comment]
Then let's make a new issue :)
