### ISSUE TITLE
'Flamingo Leg', Leg collapses with zero-rotations in a VRIK driven avatar

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#2177]
## Describe the bug
With the newly created avatar [Vernid](https://gumroad.com/l/Wphtt) by Tosca the legs seem to occasionally fold up into the avatar, instead of resting on the ground.

Of note, this seems to happen to the right leg more than the left, but it does also occur with the left at times.

## Relevant issues
Possibly #2029 - This avatar also does not have the spine bound correctly (it skips the spine and binds Chest to Spine).

## To Reproduce
Import the Vernid (although I would assume any similar armature would have the issue, as without the mesh it still flamingos)
Use an Avatar Creator on the model
Move the new avatar around with the laser (or get in it and move around)
Observe that on occasion, the foot collapses with the bones all having [0,0,0] as the rotation value.

## Expected behavior
The limb has does not collapse, and remains leg-like similar to the left leg.

## Screenshots / Video
The avatar (skinned and armature only) with the left leg collapsed.
![image](https://user-images.githubusercontent.com/1251609/117233196-807a3a80-add7-11eb-8ef1-020bd9b12a97.png)

The rotation values of the right leg when in flamingo mode
![image](https://user-images.githubusercontent.com/1251609/117233017-309b7380-add7-11eb-9447-0bcd1085b0b6.png)

The link that makes #2029 possibly relevant?
![image](https://user-images.githubusercontent.com/1251609/117233748-92101200-add8-11eb-8136-fac10f767018.png)

## Bug information (please complete the following information):
 - How often does it happen: Reliably after moving the avatar for a few seconds.
 - Does the bug persist after restarting Neos? Yes/No, it comes and goes as the avatar is used.
 - Neos Version: Beta 2021.5.5.159
 - Neos Platform: Windows
 - Link to reproduction World/Item: neosrec:///U-Earthmark/R-cd26b9e9-3205-4dac-940b-50b850a9d90c (This world contains a persisted armature with the issue, the model is paid so I can not have it exposed as a public asset. However, the armature shows the problem behavior).
 - Regression: Unsure, the avatar was released 5/3/2021, but I have noticed it reliably during that time.

## Additional context
The rotation values of the leg in question all fold to [0,0,0] when flamingo mode occurs, in this model this pivots the foot at an unnatural angle, so I do not think this is a raycast-detecting-self issue? But I really don't know so meh!

## Reporters:
Neos: Earthmark Discord: Earthmark#0314

**Comment by Frooxius** [comment]
Is the Spine bone actually bound to geometry at all or is it just a dummy bone? Sometimes they don't get assigned because they're not actual mesh bones, but rather than just dummy objects.

I'll have to add some instrumentation and check what's going on with the avatar.

**Comment by Earthmark** [comment]
Spine indeed does have geometry attached to it.
![image](https://user-images.githubusercontent.com/1251609/117392511-1335da80-aea7-11eb-9a15-a18281504996.png)

To run this test I made a child of spine, parented chest under it, and then moved the child under hips so the transform of Chest remained the same. If I moved chest out itself the chest had some issues with flipping.

**Comment by Frooxius** [comment]
Fixed in 2021.6.7.794! This was caused by internal Slerp function sometimes producing NaN's, so it's a good very general fix that should get rid of range of odd issues like this. Thanks!

**Comment by Earthmark** [comment]
Possible duplicate of #2413 as both are still occurring, although it seemed like this was resolved yesterday for a bit.
