### ISSUE TITLE
Make laser invisible when using invisible context menu submenus

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2540]
## Is your tweak request related to a problem? Please describe.
Currently, when pointing my laser at an invisible context menu (using a submenu, set to hidden), the laser still shows up for others, even though the menu does not.

## Describe what would you like tweaked
Make the interaction laser not show up for people who can't see what it is pointing at.

## Describe alternatives you've considered
Keeping it like this which would be quite odd.

## Additional Context
This could also be realized as a more general thing, applying not only to context menus, but to any kind of locally disabled object/UI.

**Comment by Frooxius** [comment]
Done in 2021.7.1.437, thanks!

**Comment by Psychpsyo** [comment]
I just checked this in a world and it seems to not be fixed. The context submenu was opened from a RootContextMenuItem and the laser still showed up.

**Comment by Frooxius** [comment]
The laser is hidden on my end when I test. Does the laser show up the entirety of the time? Is it visible when pointing at the menu or when you point at something else?

There might be a bit of a timeout before it disappears if it was previously visible.

**Comment by Psychpsyo** [comment]
I tried to recreate this just now and can't get the laser to show up anymore. So it seems to be fixed. Sorry for re-opening this issue.
