### ISSUE TITLE
Headless client 2021.7.1.498 throws exceptions after fresh install on Linux and won't fully start

### ISSUE THREAD

**Issue by glitchfur** [Neos-Metaverse/NeosPublic#2570]
## Describe the bug
Running the headless client for Neos version 2021.7.1.498 on Linux after a fresh install (i.e. no configuration files, no `Cache` or `Data` folders) throws exceptions upon start up and the prompt never appears, prohibiting control of the headless client via the console. This issue doesn't seem to occur on Windows.

## Relevant issues
I did not find any relevant issues.

## To Reproduce
1. If a previous version of the headless client was already installed, emulate a fresh install by removing it completely. I removed the directory `.steam/steamapps/common/NeosVR` entirely to achieve this. I am uncertain if only uninstalling through Steam will completely remove everything.
2. Download and install Neos headless client version 2021.7.1.498 from Steam.
3. Start the headless client. It will print some exceptions (disregarding the SteamAPI one if Steam is not running, as that is expected) and the prompt to run commands will never appear. The client must be stopped with `Ctrl+C`.

## Expected behavior
The headless client should start up normally and display a prompt.

## Log Files
See attached log file: [brometheus - 2021.7.1.498 - 2021-07-02 03_23_13.log](https://github.com/Neos-Metaverse/NeosPublic/files/6751976/brometheus.-.2021.7.1.498.-.2021-07-02.03_23_13.log)

## Screenshots / Video
No screenshots or video, the log file should contain everything that they would display anyway.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.7.1.498
 - Neos Platform: Linux
 - Link to reproduction World/Item: N/A
 - Regression: Yes. Previous versions of the headless client did not throw the exceptions I'm seeing in this version.

## Additional context
If files exist from a previous version of the headless client (cache and data files, etc.), this version will start fine, which is why I've made it a point that it only errors out when installed "fresh". I tested this on three different machines and they all threw exceptions. The Mono version in use is 6.12.0 Stable (6.12.0.122).

## Reporters:
@glitchfur

**Comment by shadowpanther** [comment]
Oh, this would break a lot of Docker installations, I suspect. At least my image comes without any game files and the headless is freshly installed, so running a freshly created container would have the effect of cleaning the cache/db/assets.

From the log it seems to lack the BEPU library?
```
Could not load file or assembly 'BEPUphysics, Version=1.4.0.0, Culture=neutral, PublicKeyToken=31f6a8732a21de19' or one of its dependencies.
```
Was the BEPU dev branch merged into the headless by accident?

**Comment by glitchfur** [comment]
> From the log it seems to lack the BEPU library?

I noticed this line as well, but I didn't want to make any assumptions as to what the issue was so I just included the whole log file.

**Comment by shiftyscales** [comment]
Is this issue specific to Linux, or is it occuring for the headless client on all platforms/Windows as well?

**Comment by shadowpanther** [comment]
Tried running the windows version, freshly installed, on a vm that never ran Neos - it runs fine.

**Comment by shadowpanther** [comment]
Fresh install of Linux headless doesn't include the required BEPUPhysics.dll:
<img width="575" alt="image" src="https://user-images.githubusercontent.com/675104/124294037-f1cc3480-db5f-11eb-8a3a-c6af056bd98f.png">

**Comment by glitchfur** [comment]
> Is this issue specific to Linux, or is it occuring for the headless client on all platforms/Windows as well?

The issue seems specific to Linux. I tried to reproduce the issue on Windows, and also had a friend try on their own Windows machine, but the issue didn't occur there.

**Comment by glitchfur** [comment]
> Fresh install of Linux headless doesn't include the required BEPUPhysics.dll:

After checking again it looks like it's actually there, just sorted differently with `ls` because the "BEPU" in "BepuPhysics.dll" is not capitalized like the other files are.

![Screenshot from 2021-07-02 11-22-20](https://user-images.githubusercontent.com/14147284/124303486-23290e00-db28-11eb-8d34-7abcab10d10d.png)

So that's probably not the source of the issue, not sure what is though.

**Comment by shadowpanther** [comment]
But Linux's filesystem is case-sensitive (by default), unlike Windows', so it might still be the source of the issue.

**Comment by glitchfur** [comment]
> But Linux's filesystem is case-sensitive (by default), unlike Windows', so it might still be the source of the issue.
> Making a symlink with a proper case allows the headless to run:

Yup, I just verified this as well. Renaming `BepuPhysics.dll` to `BEPUphysics.dll` allowed the client to run for me.

**Comment by Frooxius** [comment]
Thanks for all the info! I'm not quite sure how the file could've gotten renamed like that. I'll just rebuild the headless, which should hopefully fix this.

**Comment by glitchfur** [comment]
It seems like the issue is still present in 2021.7.3.282, sorry. :(
See the attached log file from this version: [brometheus - 2021.7.3.282 - 2021-07-03 05_03_07.log](https://github.com/Neos-Metaverse/NeosPublic/files/6757859/brometheus.-.2021.7.3.282.-.2021-07-03.05_03_07.log)

The capitalization of `BepuPhysics.dll` is the same as in the previous version.

**Comment by Frooxius** [comment]
Hmm. Is this on a fresh install? Even if you wipe all the files? It's really odd, because the capitalization is correct on my end when I push it, I have no idea what could be changing it to lowercase.

**Comment by glitchfur** [comment]
It is to the best of my knowledge a fresh install, unless the headless client stores files in other locations. I have a script that I use to update Neos, which removes the `~/.steam/steamapps/common/NeosVR` directory, and then use SteamCMD to grab the latest version of the `headless-client` branch from Steam.

**Comment by Frooxius** [comment]
I pushed an update where I renamed the file to __BepuPhysics.dll and then another where I renamed it back. See if that prods it and forces it to change the capitalization.

**Comment by glitchfur** [comment]
Has the version of those updates changed? I'm still getting 2021.7.3.282. Either way, the file name is still the same.

**Comment by Frooxius** [comment]
No the version should be the same.

**Comment by Frooxius** [comment]
I checked the Depot Manifest on Steam Pipeline, it has the correct name there as well: 
![image](https://user-images.githubusercontent.com/8838625/124344429-62139e00-dbd2-11eb-9e13-a93e813a8606.png)

Would you be able to get the DepotID and ManifestGID of the one you have installed if you still have trouble?

**Comment by glitchfur** [comment]
> No the version should be the same.

Yeah, the file name I'm getting is still the same.

> I checked the Depot Manifest on Steam Pipeline, it has the correct name there as well:

This screenshot shows the current capitalization of `BepuPhysics.dll`. Is that correct? It should be `BEPUphysics.dll`. If I rename the file or create a symbolic link for the latter capitalization, the headless client will start then.

I believe I found my depot and manifest IDs but I am unfamiliar with pulling those so I apologize if this info is incorrect:
- DepotID: `740252`
- ManifestGID: `1556858492938692267`

**Comment by Frooxius** [comment]
Oh wait, so the file is supposed to be BEPUphysics.dll instead of BepuPhysics.dll? I got it confused and thought it was the other way around. Hmm, it's a bit strange though. I'll poke around a bit and see what's up.

**Comment by Frooxius** [comment]
Ok give the latest one a try. I had to re-save the module so it gets different hash, Steam doesn't seem to want to actually update the file name capitalization if it's exactly the same (even if it's renamed to something else between builds). Hopefully should be good now.

**Comment by shadowpanther** [comment]
Can confirm, wiping the install folder and getting the latest build via steamcmd ends up with a working headless client. Thank you Froox.

**Comment by glitchfur** [comment]
Can also confirm, getting the correct file name now and the headless client starts without any modification. Thanks Froox!

**Comment by shiftyscales** [comment]
We've had a few confirmed cases of this working properly, closing the issue.
